### ISSUE TITLE
[exporter/loadbalancing] Flaky Test - TestRollingUpdatesWhenConsumeLogs

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#11116]
Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7802139871?check_suite_focus=true#step:7:2604
```
trace_exporter_test.go:569: 
        	Error Trace:	D:\a\opentelemetry-collector-contrib\opentelemetry-collector-contrib\exporter\loadbalancingexporter\trace_exporter_test.go:569
        	Error:      	"0" is not greater than "0"
        	Test:       	TestRollingUpdatesWhenConsumeTraces
--- FAIL: TestRollingUpdatesWhenConsumeTraces (0.05s)
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter	0.306s
FAIL
mingw32-make[2]: *** [../../Makefile.Common:56: test] Error 1

```

**Comment by BinaryFissionGames** [comment]
May or may not be related to this specific issue, but another flake on the same test: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7749964411?check_suite_focus=true#step:7:2794

```
=== RUN   TestRollingUpdatesWhenConsumeLogs
    log_exporter_test.go:468: 
        	Error Trace:	D:\a\opentelemetry-collector-contrib\opentelemetry-collector-contrib\exporter\loadbalancingexporter\log_exporter_test.go:468
        	Error:      	"0" is not greater than "0"
        	Test:       	TestRollingUpdatesWhenConsumeLogs
--- FAIL: TestRollingUpdatesWhenConsumeLogs (0.05s)
```

**Comment by djaglowski** [comment]
Again here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7777139651?check_suite_focus=true#step:7:2901

**Comment by djaglowski** [comment]
Here too: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7787492747?check_suite_focus=true#step:7:2962

**Comment by djaglowski** [comment]
Escalating this to a p2 due to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13220

**Comment by dmitryax** [comment]
ANother instance https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7800282398?check_suite_focus=true

**Comment by bogdandrutu** [comment]
The initial problem (race condition) was fixed before @djaglowski disabled the test :)) https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13257

Lucky the test is still flaky for a different reason, see https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7802139871?check_suite_focus=true

@djaglowski can you update the issue please ?

**Comment by djaglowski** [comment]
Issue updated.

**Comment by dmitryax** [comment]
@bogdandrutu looks like it's still happening https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7814063100?check_suite_focus=true

**Comment by djaglowski** [comment]
A couple more times:
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7816211433?check_suite_focus=true
https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7819464925?check_suite_focus=true#step:7:2597

**Comment by bogdandrutu** [comment]
All of them are for `TestRollingUpdatesWhenConsumeTraces` not for `TestRollingUpdatesWhenConsumeLogs`. Looks like a problem on the Traces.

**Comment by dmitryax** [comment]
Right. I created another issue for traces https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13331
