### ISSUE TITLE
[receiver/hostmetrics] Paging scraper queries different procfs from within container

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-collector-contrib#15998]
## Description

The paging scraper hardcodes the file to query the swap information from. This is seen [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/eeb81351cb7763180520faa7bec5d970a5a0818e/receiver/hostmetricsreceiver/internal/scraper/pagingscraper/pagefile_linux.go#L29). 

When querying from a chrooted environment (e.g. container), it does not query the correct file.

## Expected Result

Ideally the paging scraper is consistent with other scrapers, querying the same proc filesystem as the other scrapers. 

Potential solution is to utilise the `root_path` config propsed in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5879. Another possible solution is to utilise the `$HOST_PROC` var that gopsutil expects. 

### Collector version

0.63.0

## Environment
OS: All Linux

**Comment by dmitryax** [comment]
This should be also controlled by the new `root_path` option. @jamesmoessis will you have a chance to work on this issue as a follow up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16026?

**Comment by jamesmoessis** [comment]
I should be able to work on it, might not be soon though. You can assign it to me and I'll get around to it.

**Comment by dmitryax** [comment]
Thanks @jamesmoessis. Assigned

**Comment by dmitryax** [comment]
@jamesmoessis this can be closed now since https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5879 is resolved, right?

**Comment by jamesmoessis** [comment]
@dmitryax no, I think this is still an issue. Specifically the paging scraper hard codes this value, and doesn't use the `root_path` variable. Here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/eeb81351cb7763180520faa7bec5d970a5a0818e/receiver/hostmetricsreceiver/internal/scraper/pagingscraper/pagefile_linux.go#L29
