### ISSUE TITLE
googlecloudmonitoringreceiver doesn't get attributes for the metrics

### ISSUE THREAD

**Issue by HazemAbdelmagid** [open-telemetry/opentelemetry-collector-contrib#37742]
### Component(s)

receiver/googlecloudmonitoring

## Description
I have been trying to use googlecloudmonitoring receiver to collect metrics related to memorystore and then forward them to prometheus but when I try to query the metrics I can't find any attributes in the metrics which doesn't allow us to filter the metrics if we have multiple instances running in memorystore, example:

`openetelemetry_operator_system_redis_googleapis_com_server_uptime{instance="collector.opentelemetry-operator-system.svc:9090", job="scrapeconfig/prometheus-system/otel-scrape-config"}`

```
## Steps to Reproduce
googlecloudmonitoring:
        collection_interval: 5m
        project_id: {{ projectName }}
        metrics_list:
        - metric_name: "redis.googleapis.com/stats/cpu_utilization"
```
## Expected Result
googlecloudmonitoring receiver should be able to collect the listed metrics and provide attributes for each metric to allow filteration.

## Actual Result
`openetelemetry_operator_system_redis_googleapis_com_server_uptime{instance="collector.opentelemetry-operator-system.svc:9090", job="scrapeconfig/prometheus-system/otel-scrape-config"}`

### Collector version

0.118.0

## Environment
GKE Cluster

### OpenTelemetry Collector configuration

```yaml
config:
    exporters:
      debug:
        verbosity: detailed
      googlecloudpubsub:
        project: <redacted>
        topic: projects/<redacted>/topics/metrics-pubsub
    processors:
      batch:
        timeout: 5s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 10
    receivers:
      googlecloudmonitoring:
        collection_interval: 5m
        project_id: <redacted>
        metrics_list:
        - metric_name: "redis.googleapis.com/instance/stats/cpu_utilization"
    service:
      pipelines:
        metrics:
          exporters:
          - googlecloudpubsub
          - debug
          processors:
          - batch
          - memory_limiter
          receivers:
          - googlecloudmonitoring
```

### Log output

```shell
No logs as there is no errors but only the metric with missing attributes.

`openetelemetry_operator_system_redis_googleapis_com_server_uptime{instance="collector.opentelemetry-operator-system.svc:9090", job="scrapeconfig/prometheus-system/otel-scrape-config"}`
```

**Comment by dashpole** [comment]
What collector version?  A similar issue was fixed recently: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35711

**Comment by HazemAbdelmagid** [comment]
Yeah I am aware of this issue so at start I was using version 0.116.1 then I moved to 0.118.0 and still the same issue

**Comment by HazemAbdelmagid** [comment]
@dashpole so I have tried to just get one metrics from a memorystore redis instance and enabled debug log on the otel collector, I got the attributes normally in the logs using version 0.119.0 as shown in the attached files:

[otel-debug.txt](https://github.com/user-attachments/files/18764564/otel-debug.txt)

[otel-collector.txt](https://github.com/user-attachments/files/18764586/otel-collector.txt)

However when the metrics passed the pubsub and got received on the other end using another otel collector then got scraped by prometheus, prometheus doesn't show any of these attributes as below:

<img width="1056" alt="Image" src="https://github.com/user-attachments/assets/30d172aa-71d9-4288-859a-d639fe9ef6ef" />

**Comment by dashpole** [comment]
Hmmm... seems like "role" appears in resource attributes instead of metric labels.

**Comment by dashpole** [comment]
Probably an issue with how https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35828 was implemented

**Comment by eenchev** [comment]
Bumping this, as mapping the metric attributes can be an issue. Perhaps a flag that controls the behavior - whether attributes should be part of the resource, or datapoints?
