### ISSUE TITLE
Receiver : Prometheus : Authorization Password not replaced

### ISSUE THREAD

**Issue by joaolcorreia** [open-telemetry/opentelemetry-collector-contrib#40916]
## Description
When you have a receiver prometheus that requires authentication the password is not being adding to the header `authorization: Basic xxxxxxx`

The xxxxx is replaces the username:<secret>  and shows <secret> instead of replacing the password given in the config file

## Steps to Reproduce

Configure a prometheus receiver with authentication pointing to Pipedream and inspect the headers.
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'warpstream'
          metrics_path: '/api/v1/monitoring/prometheus/virtual_clusters/xxxxxx'
          scheme: https
          basic_auth:
            username: prometheus
            password: "xxxxxxxxx"
          scrape_interval: 60s
          static_configs:
            - targets: ['xxxxx.m.pipedream.net']
              labels:
                service: 'warpstream'
                environment: 'production'
```

## Expected Result
You should see `username:password` base 64 encoded 

## Actual Result
You see `username:<secret>` you see `<secret>` instead of the actual secret.

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

**Comment by axw** [comment]
I can reproduce this issue.

Searching for `<secret>` in the Prometheus code base, I came across https://github.com/prometheus/common/blob/75c3814dc66c571cc82cee2d3a6bf5f37ee73f1a/config/config.go#L35-L44

It looks like it's related to how the config gets re-marshaled to YAML when reloading. See https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b467589b3c634b54be5d110e9fc36cc0a5a1a47d/receiver/prometheusreceiver/config.go#L147-L158

There's a global (MarshalSecretValue) that can be set to true to marshal these secrets as-is. I don't know if that would have any other negative side-effects.

**Comment by ArthurSens** [comment]
Seems like a duplicate of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40520, the fix is being worked on in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40780

**Comment by ridwanmsharif** [comment]
> It looks like it's related to how the config gets re-marshaled to YAML when reloading. See
> 
> [opentelemetry-collector-contrib/receiver/prometheusreceiver/config.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b467589b3c634b54be5d110e9fc36cc0a5a1a47d/receiver/prometheusreceiver/config.go#L147-L158)
> 
> Lines 147 to 158 in [b467589](/open-telemetry/opentelemetry-collector-contrib/commit/b467589b3c634b54be5d110e9fc36cc0a5a1a47d)
> 
>  func reloadPromConfig(dst *PromConfig, src any) error { 
>  	yamlOut, err := yaml.Marshal(src) 
>  	if err != nil { 
>  		return fmt.Errorf("prometheus receiver: failed to marshal config to yaml: %w", err) 
>  	} 
>  	newCfg, err := promconfig.Load(string(yamlOut), slog.Default()) 
>  	if err != nil { 
>  		return fmt.Errorf("prometheus receiver: failed to unmarshal yaml to prometheus config object: %w", err) 
>  	} 
>  	*dst = PromConfig(*newCfg) 
>  	return nil 
>  } 
> There's a global (MarshalSecretValue) that can be set to true to marshal these secrets as-is. I don't know if that would have any other negative side-effects.

We don't even have to use a global setting here, we can update the `reloadPromConfig` to use a custom marshaller to preserve the secret value on reload. See here for an example: https://github.com/GoogleCloudPlatform/ops-agent/blob/1c8f5801ca9e65e9e45dcdb90e570fc6d86fd908/confgenerator/prometheus.go#L137-L153

I updated the PR with the fix with this suggestion: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40780#discussion_r2169712175

**Comment by erikburt** [comment]
@ridwanmsharif - I will try this out. Thanks 🙏

**Comment by erikburt** [comment]
Seems to have worked - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40780

**Comment by songy23** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40780

**Comment by lifttocode** [comment]
Hi @songy23 I'm still experiencing this issue with the otel/opentelemetry-collector-contrib:0.134.1 image. The basic auth password is still being replaced with <secret> when scraping endpoints that require authentication. cc @erikburt 

Here's what I'm observing:
1. Environment: Kubernetes with OpenTelemetry Collector v0.134.1 and Target Allocator v0.132.0
2. Configuration: Using ServiceMonitor with basic_auth referencing Kubernetes secrets
3. Issue: The password field is being replaced with <secret> in the actual HTTP requests

Packet capture showing the issue: Authorization: Basic bWV0cmljOjxzZWNyZXQ+ → When decoded, this shows `metric:<secret>` instead of the actual password.

Questions:
1. Was the fix from PR #40780 (merged July 1, 2025) included in the v0.134.0 release? If not, which release version will include this fix?
2. Does the Target Allocator also need to be updated to a specific version to resolve this issue?

Any clarification on when this fix will be available in a stable release would be greatly appreciated. Thank you!

**Comment by erikburt** [comment]
> Was the fix from PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40780 (merged July 1, 2025) included in the v0.134.0 release? If not, which release version will include this fix?

This was released in the [v0.130.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.130.0) release of this repository. Which has been included in the past couple releases everywhere else. For example:
- https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.131.0

---

I don't know enough to diagnose this further, but it seems like otel operator could be causing marshaling issues as:
- prometheus receiver scrapeConfig is loaded into a custom v1beta1 type - https://github.com/open-telemetry/opentelemetry-operator/blob/2bdd0353b3967518c12f0c9b4b7e3079ff9d17f4/internal/manifests/targetallocator/configmap.go#L213C26-L213C30
- v1beta1 has JSON marshalling which wouldn't have been fixed by the above changes - https://github.com/open-telemetry/opentelemetry-operator/blob/2bdd0353b3967518c12f0c9b4b7e3079ff9d17f4/apis/v1beta1/config.go#L69

^ This is all speculation from someone who's far out of their depth LOL
