### ISSUE TITLE
[processor/tailsampling] Remove static decision wait for all traces

### ISSUE THREAD

**Issue by csmarchbanks** [open-telemetry/opentelemetry-collector-contrib#43876]
### Component(s)

processor/tailsampling

### Is your feature request related to a problem? Please describe.

The decision wait implemented in the tailsampling processor provides the user with basically a pick your poison situation, and we could do better. Specifically:
1. Lowering the decision wait means that some traces will not be sampled appropriately, for example, spans that are longer than the decision wait will not be sampled appropriately as a decision will already have been made.
2. Increasing the decision wait increases the cost of running the tail sampling processor as traces will be kept in memory longer. In addition, it will add additional delay for traces that could have been sampled sooner.

### Describe the solution you'd like

Remove the decision wait to instead:
1. Support early sampling for most policies - if a decision can be made on a partial set of spans sample it right away to avoid waiting for the full decision wait before making a decision
2. For long running traces use a max span count and idle time to force a decision that did not match any of the early decisions

### Describe alternatives you've considered

We could leave the decision wait in place but still support early decisions. This would be an improvement to what we have today (and implementation wise, a stepping stone towards the final solution). The downside is that any chosen decision wait does not work well for long running traces where the correct decision may not be known for minutes or even hours.

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

**Comment by axw** [comment]
This sounds good to me, and along the lines of what we implemented in Elastic APM:

- We set a TTL for each span, which is the upper limit for a decision wait. Any traces that don't receive a sampling decision before the TTL just age out. See also https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/42326.
- Both positive and negative sampling decisions may be made before that TTL. In our implementation we're using reservoir sampling, so either a (negative) sampling decision is made when (not) adding to the reservoir, or a sampling decision is made when the reservoir is flushed. That's effectively just a policy implementation though.

**Comment by csmarchbanks** [comment]
I am still working towards this. #44878 being merged is a big step in the right direction, but does not completely solve the issue.

**Comment by csmarchbanks** [comment]
The work done in #44878 has been successful in our deployments and I don't think we need to do more work now. Introducing root-span based sampling has allowed us to increase our base decision_wait to accept longer traces without requiring more resources.

In the future there could be another optimization to support early decisions without a root span, but that will come with more complexity and the current solution does well on more than 95% of traces we receive.

**Comment by atoulme** [comment]
Understood ; fwiw if you see success related to performance, please use microbenchmarks to sustain your PRs, it'll be easier to reason about the performance.
